### ISSUE TITLE
File already Exists

### ISSUE THREAD

**Issue by puffofsmoke** [averkij/a-studio#1]
Делаю
docker pull lingtrain/aligner:v4
Загружаю текстовый файл и...

![image](https://user-images.githubusercontent.com/34794593/126877765-3b03a937-202a-4077-b407-bf8803f20eeb.png)

После вот такого предупреждения ничего не происходит
Причём оно вылазит на любой текстовый файл

**Comment by puffofsmoke** [comment]
Данные при этом безуспешно пытались отправиться на http://95.181.157.134:5000/items/111/raw/zh

**Comment by puffofsmoke** [comment]
Пофиксил

**Comment by averkij** [comment]
Не тот образ был, судя по скриншоту.

**Comment by pinkykitten** [comment]
I had the same problem when uploading at URL: http://localhost:9999/user/hi/docs/en/ru
<img width="1327" alt="Screen Shot 2022-01-25 at 12 32 24 AM" src="https://user-images.githubusercontent.com/7857371/150835230-291ffa0a-ecaf-409a-8fd5-cdb78fa0cda2.png">
