### ISSUE TITLE
Incorrect path to sources

### ISSUE THREAD

**Issue by AigizK** [averkij/a-studio#2]
How to reproduce:
1. run docker on local machine(docker run -p 8004:80 lingtrain/aligner:v4)
2. open a site on the browser

![image](https://user-images.githubusercontent.com/1628540/130564694-e176923f-9310-49bc-9c0d-73cd7d0d5768.png)

**Comment by averkij** [comment]
It's because you've started docker on 8004 port instead of 80.

Whats's wrong with the default 80 port? It's seems to be working fine.

**Comment by averkij** [comment]
To run the docker on another port (not 80) you need to change API_URL parameter in config.js and rebuild the docker container.
