### ISSUE TITLE
Exception (500 code) when trying to preview a book

### ISSUE THREAD

**Issue by BorisNA** [averkij/a-studio#4]
Previewing a book after the successful alignment generates an exception.

Steps to reproduce:
1. Upload provided de and ru files
2. Make the automatic alignment (should work without manual editing)
3. Open the book creation section, select "Paragraph structure" from "from" (i.e. German)
4. Try to preview the book - exception

Exporting a book works Ok though, and previewing from "to" (i.e. Russian)

Tested with both 0.6.0 and 0.6.1 aligners

[exception.txt](https://github.com/averkij/a-studio/files/7108043/exception.txt)
[test_de.txt](https://github.com/averkij/a-studio/files/7108044/test_de.txt)
[test_ru.txt](https://github.com/averkij/a-studio/files/7108045/test_ru.txt)

**Comment by averkij** [comment]
Problem was in get_paragraphs_polybook which is obsolete. Changed to get_paragraphs method which is already used in export.

Fixed in master branch of a-studio and in lingtrain-aligner==6.2.
